spring:
  datasource:
    url: jdbc:h2:file:./stockapp.h2;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
    username: cisc191
    password: honors
    driverClassName: org.h2.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      # ddl-auto: create-drop
      ddl-auto: update
    console:
      enabled: true
      # default path: h2-console
      path: /h2-ui

server:
  port : 8081